### ISSUE TITLE
ParteA

### ISSUE THREAD

**Issue by Nicolas-Trom** [IngenieriaSoftwareTeam/practica1-Nicolas-Trom#1]
git init
git clone https://github.com/IngenieriaSoftwareTeam/practica1-Nicolas-Trom.git
git add .
git commit -m "add: Nombre y Numero de esudiante, Nodo 1"
git checkout -b feature1
git add .
git commit -m "add: Nodo 2"
git checkout -b feature2
git add .
git commit -m "add: Nodo 3"
git checkout -b fix2
git add .
git commit - m "add: Nodo 4"
git checkout feature1
git add .
git commit -m "add: Nodo 5"
git checkout main
git merge feature1
git add .
git commit -m "add: Nodo 6"
git checkout feature2
git add .
git commit -m "add: Nodo 7"
git checkout main
git merge feature2
git add .
git commit -m "add: Nodo 8"

**Comment by benjaneri** [comment]
Parte A: Muy buen trabajo, un detalle, la rama “feature2” la creaste parado en “feature1”, las ramas comienzan desde donde estas parado.

3.5/4
