### ISSUE TITLE
ParteB

### ISSUE THREAD

**Issue by Nicolas-Trom** [IngenieriaSoftwareTeam/practica1-Nicolas-Trom#2]
![Captura desde 2023-09-07 11-15-37](https://github.com/IngenieriaSoftwareTeam/practica1-Nicolas-Trom/assets/63602035/90c814c3-fda0-469d-953d-ab5efd2e78c1)

**Comment by benjaneri** [comment]
Parte B: Perfecto, lo único un detalle al hacer el merge el archivo “implmented_features.md” quedó como con la interfaz para resolver el conflicto.

4/4
